import { TemplateRenderer, createTemplateRenderer } from '@/services/template-renderer';
import type { WorkplanTemplate } from '@/interfaces/workplan-template';

describe('TemplateRenderer', () => {
  let renderer: TemplateRenderer;
  let mockFileSystem: jest.Mocked<{ readFile: (path: string, encoding: BufferEncoding) => Promise<string> }>;

  beforeEach(() => {
    mockFileSystem = {
      readFile: jest.fn(),
    };

    renderer = new TemplateRenderer({
      fileSystem: mockFileSystem,
    });
  });

  describe('render', () => {
    const mockTemplate: WorkplanTemplate = {
      name: 'test-template',
      version: '1.0.0',
      header: '# WORKPLAN-{{featureId}}: {{featureName}}',
      sections: [
        {
          id: 'description',
          title: 'Feature Description',
          content: '{{featureDescription}}',
          order: 1,
        },
        {
          id: 'tasks',
          title: 'Task Breakdown',
          content: '{{taskBreakdown}}',
          order: 2,
        },
      ],
      footer: 'Generated by {{generator}}',
      defaults: {
        generator: 'mulder-workplans',
      },
    };

    it('should render template with variables', async () => {
      const variables = {
        featureId: 'TEST123',
        featureName: 'Test Feature',
        featureDescription: 'This is a test feature',
        taskBreakdown: '- [ ] Task 1\n- [ ] Task 2',
      };

      const result = await renderer.render(mockTemplate, variables);

      expect(result).toContain('# WORKPLAN-TEST123: Test Feature');
      expect(result).toContain('## Feature Description');
      expect(result).toContain('This is a test feature');
      expect(result).toContain('## Task Breakdown');
      expect(result).toContain('- [ ] Task 1');
      expect(result).toContain('Generated by mulder-workplans');
    });

    it('should use template defaults for missing variables', async () => {
      const variables = {
        featureId: 'TEST123',
        featureName: 'Test Feature',
        featureDescription: 'Test description',
        taskBreakdown: 'Test tasks',
      };

      const result = await renderer.render(mockTemplate, variables);

      expect(result).toContain('Generated by mulder-workplans');
    });

    it('should throw error when template is null', async () => {
      await expect(renderer.render(null as any, {})).rejects.toThrow(
        'Template is required for rendering'
      );
    });

    it('should throw error when template has no sections', async () => {
      const invalidTemplate = { ...mockTemplate, sections: [] };

      await expect(renderer.render(invalidTemplate, {})).rejects.toThrow(
        'Template must contain at least one section'
      );
    });

    it('should sort sections by order', async () => {
      const templateWithOrdering: WorkplanTemplate = {
        ...mockTemplate,
        sections: [
          {
            id: 'second',
            title: 'Second Section',
            content: 'Second content',
            order: 2,
          },
          {
            id: 'first',
            title: 'First Section',
            content: 'First content',
            order: 1,
          },
        ],
      };

      const variables = {
        featureId: 'TEST',
        featureName: 'Test',
      };

      const result = await renderer.render(templateWithOrdering, variables);
      const firstSectionIndex = result.indexOf('## First Section');
      const secondSectionIndex = result.indexOf('## Second Section');

      expect(firstSectionIndex).toBeLessThan(secondSectionIndex);
    });
  });

  describe('renderFromString', () => {
    it('should substitute variables in string template', () => {
      const template = 'Hello {{name}}, welcome to {{project}}!';
      const variables = {
        name: 'John',
        project: 'Mulder',
      };

      const result = renderer.renderFromString(template, variables);

      expect(result).toBe('Hello John, welcome to Mulder!\n');
    });

    it('should leave unknown variables unchanged', () => {
      const template = 'Hello {{name}}, your score is {{unknown}}!';
      const variables = {
        name: 'John',
      };

      const result = renderer.renderFromString(template, variables);

      expect(result).toBe('Hello John, your score is {{unknown}}!\n');
    });

    it('should throw error for empty template', () => {
      expect(() => renderer.renderFromString('', {})).toThrow(
        'Template content is required'
      );
    });
  });

  describe('renderFromFile', () => {
    it('should read file and render template', async () => {
      const templatePath = '/absolute/path/to/template.md';
      const templateContent = 'Project: {{projectName}}';
      const variables = { projectName: 'Mulder' };

      mockFileSystem.readFile.mockResolvedValue(templateContent);

      const result = await renderer.renderFromFile(templatePath, variables);

      expect(result).toBe('Project: Mulder\n');
      expect(mockFileSystem.readFile).toHaveBeenCalledWith(templatePath, 'utf8');
    });

    it('should throw error for relative path', async () => {
      await expect(
        renderer.renderFromFile('relative/path', {})
      ).rejects.toThrow('Template path must be absolute');
    });

    it('should throw error for empty path', async () => {
      await expect(renderer.renderFromFile('', {})).rejects.toThrow(
        'Template path is required'
      );
    });

    it('should throw error when file not found', async () => {
      const templatePath = '/absolute/path/to/missing.md';
      const error = new Error('File not found') as any;
      error.code = 'ENOENT';

      mockFileSystem.readFile.mockRejectedValue(error);

      await expect(
        renderer.renderFromFile(templatePath, {})
      ).rejects.toThrow(`Template file not found: ${templatePath}`);
    });

    it('should throw error for other file system errors', async () => {
      const templatePath = '/absolute/path/to/template.md';
      const error = new Error('Permission denied');

      mockFileSystem.readFile.mockRejectedValue(error);

      await expect(
        renderer.renderFromFile(templatePath, {})
      ).rejects.toThrow('Failed to read template file: Permission denied');
    });
  });

  describe('markdown normalization', () => {
    it('should normalize excessive newlines', () => {
      const template = 'Line 1\n\n\n\nLine 2\n\n\n\n\nLine 3';
      const result = renderer.renderFromString(template, {});

      expect(result).toBe('Line 1\n\nLine 2\n\nLine 3\n');
    });

    it('should remove trailing spaces from lines', () => {
      const template = 'Line with spaces   \nAnother line  ';
      const result = renderer.renderFromString(template, {});

      expect(result).toBe('Line with spaces\nAnother line\n');
    });
  });

  describe('createTemplateRenderer factory', () => {
    it('should create renderer instance', () => {
      const renderer = createTemplateRenderer();

      expect(renderer).toBeInstanceOf(TemplateRenderer);
    });

    it('should create renderer with options', () => {
      const options = { fileSystem: mockFileSystem };
      const renderer = createTemplateRenderer(options);

      expect(renderer).toBeInstanceOf(TemplateRenderer);
    });
  });
});